### ISSUE TITLE
Why does 'ocrd-tesserocr-deskew' need 'osd.traineddata' as a model?

### ISSUE THREAD

**Issue by VolkerHartmann** [OCR-D/ocrd_tesserocr#106]
Without this model the deskewing fails with the message:

```
Traceback (most recent call last):
  File "/usr/bin/ocrd-tesserocr-deskew", line 8, in <module>
    sys.exit(ocrd_tesserocr_deskew())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd_tesserocr/cli.py", line 40, in ocrd_tesserocr_deskew
    return ocrd_cli_wrap_processor(TesserocrDeskew, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd/decorators.py", line 54, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd/processor/base.py", line 56, in run_processor
    processor.process()
  File "/usr/lib/python3.6/site-packages/ocrd_tesserocr/deskew.py", line 75, in process
    psm=PSM.AUTO_OSD
  File "tesserocr.pyx", line 1189, in tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1202, in tesserocr.PyTessBaseAPI._init_api
RuntimeError: Failed to init API, possibly an invalid tessdata path: /tess/data/path
```

**Comment by bertsky** [comment]
Simply because Tesseract's deskewing/orientation analysis needs this model (OSD = _orientation and script analysis_). 

I fail to see the problem. Do you want `osd.traineddata` as an install-time dependency? If you use ocrd_all, `make deps-ubuntu` or `make install-tesseract` encapsulates that.

**Comment by kba** [comment]
What @bertsky said, plus you can do `sudo apt-get install tesseract-ocr-osd` by hand. Should we add that to the README or is it installed as a dependency anyway?

**Comment by bertsky** [comment]
> or is it installed as a dependency anyway

In Debian/Ubuntu, `tesseract-ocr` depends on `tesseract-ocr-osd`

**Comment by VolkerHartmann** [comment]
Everything is fine. I was a little bit astonished about, as I didn't expect any model for deskewing. I set the TESSDATA_PREFIX variable to my own directory so I missed the osd.traineddata. I already fixed this.

**Comment by stweil** [comment]
The model is used for the script detection part. It was trained with selected frequently used glyphs for Latin, Greek, Cyrillic, Arabic, Chinese etc. and can thus make an estimation which scripts are used.
