### ISSUE TITLE
TypeError: object of type 'list_reverseiterator' has no len()

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_tesserocr#112]
With [this workspace](https://github.com/OCR-D/ocrd_tesserocr/files/4214468/bug-list_reverseiterator-has-no-len-abdipre_774039221.tar.gz) I get the following error:

```
% ocrd-tesserocr-recognize -I OCR-D-GT-PAGE-BINPAGE-sauvola -O OCR-D-OCR-TESS-frk+deu-OCR-D-GT-PAGE-BINPAGE-sauvola -p '{ "textequiv_level" : "glyph", "overwrite_words": true, "model" : "frk+deu" }'
16:14:59.323 INFO ocrd.workspace_validator - input_file_grp=['OCR-D-GT-PAGE-BINPAGE-sauvola'] output_file_grp=['OCR-D-OCR-TESS-frk+deu-OCR-D-GT-PAGE-BINPAGE-sauvola']
16:14:59.940 INFO processor.TesserocrRecognize - Using model 'frk+deu' in /usr/share/tesseract//tessdata/ for recognition at the glyph level
16:14:59.940 INFO processor.TesserocrRecognize - INPUT FILE 0 / 00000055
16:14:59.982 INFO processor.TesserocrRecognize - Page '00000055' images will use 300 DPI from image meta-data
16:14:59.982 INFO processor.TesserocrRecognize - Processing page '00000055'
Traceback (most recent call last):
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/bin/ocrd-tesserocr-recognize", line 8, in <module>
    sys.exit(ocrd_tesserocr_recognize())
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/ocrd_tesserocr/cli.py", line 36, in ocrd_tesserocr_recognize
    return ocrd_cli_wrap_processor(TesserocrRecognize, *args, **kwargs)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/ocrd/decorators.py", line 60, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/ocrd/processor/base.py", line 57, in run_processor
    processor.process()
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/ocrd_tesserocr/recognize.py", line 189, in process
    page_update_higher_textequiv_levels(maxlevel, pcgts)
  File "/home/mike/.virtualenvs/bug-list_reverseiterator-has-no-len/lib/python3.7/site-packages/ocrd_tesserocr/recognize.py", line 525, in page_update_higher_textequiv_levels
    word_conf /= len(glyphs)
TypeError: object of type 'list_reverseiterator' has no len()
```

Using ocrd-tesserocr 0.8.0:
```
% pip list | grep tess     
ocrd-tesserocr         0.8.0     
tesserocr              2.5.0  
```

**Comment by mikegerber** [comment]
The problem seems to be twofold:

1. The code part in https://github.com/OCR-D/ocrd_tesserocr/blame/master/ocrd_tesserocr/recognize.py#L516 seems to be erroneous if word/lines/regions have a reading direction explicitly assigned, as in the GT PAGE I'm using here (to test OCR with GT segmentation)
2. `reversed(glyphs)` is not a list but a `list_reverseiterator` and so the `len()` is not possible in https://github.com/OCR-D/ocrd_tesserocr/blame/master/ocrd_tesserocr/recognize.py#L525

**Comment by mikegerber** [comment]
👀 @bertsky

**Comment by mikegerber** [comment]
A note about the the first part: Reading direction is always left-to-right in the XML, it's just assigned on the regions explicitly, so the glyphs shouldn't be reversed.

**Comment by bertsky** [comment]
Thanks @mikegerber for your analysis, you are absolutely right. Badly tested I must admit.

**Comment by mikegerber** [comment]
#113 looks good:
~~~
% ocrd-tesserocr-recognize -I OCR-D-GT-PAGE-BINPAGE-sauvola -O OCR-D-OCR-TESS-frk+deu-OCR-D-GT-PAGE-BINPAGE-sauvola -p '{ "textequiv_level" : "glyph", "overwrite_words": true, "model" : "frk+deu" }'
17:41:09.080 INFO ocrd.workspace_validator - input_file_grp=['OCR-D-GT-PAGE-BINPAGE-sauvola'] output_file_grp=['OCR-D-OCR-TESS-frk+deu-OCR-D-GT-PAGE-BINPAGE-sauvola']
17:41:09.685 INFO processor.TesserocrRecognize - Using model 'frk+deu' in /usr/share/tesseract//tessdata/ for recognition at the glyph level
17:41:09.686 INFO processor.TesserocrRecognize - INPUT FILE 0 / 00000055
17:41:09.724 INFO processor.TesserocrRecognize - Page '00000055' images will use 300 DPI from image meta-data
17:41:09.724 INFO processor.TesserocrRecognize - Processing page '00000055'
17:41:14.962 INFO processor.TesserocrRecognize - INPUT FILE 1 / 00000056
17:41:14.993 INFO processor.TesserocrRecognize - Page '00000056' images will use 300 DPI from image meta-data
17:41:14.993 INFO processor.TesserocrRecognize - Processing page '00000056'
17:41:20.001 INFO processor.TesserocrRecognize - INPUT FILE 2 / 00000057
17:41:20.045 INFO processor.TesserocrRecognize - Page '00000057' images will use 300 DPI from image meta-data
17:41:20.045 INFO processor.TesserocrRecognize - Processing page '00000057'
17:41:24.132 INFO processor.TesserocrRecognize - INPUT FILE 3 / 00000058
17:41:24.162 INFO processor.TesserocrRecognize - Page '00000058' images will use 300 DPI from image meta-data
17:41:24.163 INFO processor.TesserocrRecognize - Processing page '00000058'
17:41:29.060 INFO ocrd.workspace - Saving mets '/home/mike/devel/bug-list_reverseiterator-has-no-len/abdipre_774039221/mets.xml'
~~~
