### ISSUE TITLE
"segment-line" produces "GeometryCollection" (which has no coords)

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd_tesserocr#119]
I receive the following error when running `segment-line`:
```
Traceback (most recent call last):
  File "/home/kmw/OCR-D/env/bin/ocrd-tesserocr-segment-line", line 8, in <module>
    sys.exit(ocrd_tesserocr_segment_line())
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/ocrd_tesserocr/cli.py", line 26, in ocrd_tesserocr_segment_line
    return ocrd_cli_wrap_processor(TesserocrSegmentLine, *args, **kwargs)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/ocrd/decorators.py", line 54, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/ocrd/processor/base.py", line 57, in run_processor
    processor.process()
  File "/home/kmw/OCR-D/env/lib/python3.7/site-packages/ocrd_tesserocr/segment_line.py", line 115, in process
    line_polygon = line_poly.exterior.coords
AttributeError: 'GeometryCollection' object has no attribute 'exterior'
```
on the image
![FILE_0024_ORIGINAL](https://user-images.githubusercontent.com/26707219/75980097-21264f00-5ee2-11ea-871e-71563ba7f196.jpg)

**Comment by bertsky** [comment]
Are you sure this image is the one processed by `segment-line`? It should be a (binarized) region image. Maybe you want to run `ocrd-segment-extract-regions` on that (page of the) workspace...

**Comment by bertsky** [comment]
I could reproduce, but please try #120 yourself, there might be more cases.
