### ISSUE TITLE
TESSDATA_PREFIX is interpreted incorrectly

### ISSUE THREAD

**Issue by kba** [OCR-D/ocrd_tesserocr#129]
I'm trying to get the https://github.com/bertsky/workflow-configuration/blob/master/crop-anyocr-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-segment-tesseract-ocropy-dewarp-ocr-ocropy-tesseract.mk running on https://github.com/OCR-D/assets/tree/master/data/kant_aufklaerung_1784/data

```sh
ocrd-make -f gt-binarize-page-olena-sauvola-denoise-ocropy-deskew-page-ocropy-clip-deskew-region-tesseract-resegment-dewarp-ocr-ocropy-tesseract-extract-lines.mk INPUT
=OCR-D-IMG LOGLEVEL=DEBUG
```

If I set `TESSDATA_PREFIX` like it is supposed to, to the parent directory of `tessdata`

```
19:38:21.064 DEBUG processor.TesserocrRecognize - TESSDATA: /home/kba/ocrd_all/venv/share/, installed Tesseract models: ['tessdata/Fraktur_50000000.334_450937-best', 'tess
data/Fraktur_50000000.334_450937-fast', 'tessdata/best/Fraktur_50000000.334_450937', 'tessdata/eng', 'tessdata/equ', 'tessdata/fast/Fraktur_50000000.334_450937', 'tessdata
/osd', 'tessdata/script/Fraktur']
Traceback (most recent call last):
  File "/home/kba/ocrd_all/venv/bin/ocrd-tesserocr-recognize", line 8, in <module>
    sys.exit(ocrd_tesserocr_recognize())
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/cli.py", line 36, in ocrd_tesserocr_recognize
    return ocrd_cli_wrap_processor(TesserocrRecognize, *args, **kwargs)
  File "/home/kba/monorepo/core/ocrd/ocrd/decorators.py", line 54, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/kba/monorepo/core/ocrd/ocrd/processor/base.py", line 60, in run_processor
    processor.process()
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/recognize.py", line 87, in process
    raise Exception("configured model " + sub_model + " is not installed")
Exception: configured model script/Fraktur is not installed
```

If I set `TESSDATA_PREFIX=$TESSDATA_PREFIX/tessdata`, it still cannot find the model:

```
19:41:33.510 DEBUG processor.TesserocrRecognize - TESSDATA: /home/kba/ocrd_all/venv/share/tessdata/, installed Tesseract models: ['Fraktur_50000000.334_450937-best', 'Frak
tur_50000000.334_450937-fast', 'best/Fraktur_50000000.334_450937', 'eng', 'equ', 'fast/Fraktur_50000000.334_450937', 'osd', 'script/Fraktur']
Traceback (most recent call last):
  File "/home/kba/ocrd_all/venv/bin/ocrd-tesserocr-recognize", line 8, in <module>
    sys.exit(ocrd_tesserocr_recognize())
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/cli.py", line 36, in ocrd_tesserocr_recognize
    return ocrd_cli_wrap_processor(TesserocrRecognize, *args, **kwargs)
  File "/home/kba/monorepo/core/ocrd/ocrd/decorators.py", line 54, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/kba/monorepo/core/ocrd/ocrd/processor/base.py", line 60, in run_processor
    processor.process()
  File "/home/kba/ocrd_all/venv/lib/python3.6/site-packages/ocrd_tesserocr/recognize.py", line 87, in process
    raise Exception("configured model " + sub_model + " is not installed")
Exception: configured model script/Latin is not installed
Makefile:307: recipe for target 'OCR-D-OCR-TESS-Fraktur+Latin-BINPAGE-sauvola-DENOISE-ocropy-DESKEW-tesseract-DESKEW-ocropy-CLIP-DESKEW-tesseract-DESKEW-ocropy-RESEG-DEWAR
P' failed
```

Has somebody an idea what I am doing wrong?

**Comment by kba** [comment]
> Has somebody an idea what I am doing wrong?

Classical case of opening an issue only to realize my mistake. `script/Latin` is not in `TESSDATA_PREFIX/tessdata`...

But the wrong interpretation of `TESSDATA_PREFIX` persists. Is this an issue with https://github.com/sirfz/tesserocr/ ?

**Comment by bertsky** [comment]
The problem with your diagnostics is a bug in the debug statement :-)

The line involved with `TESSDATA: ...` uses tesserocr's `get_languages()` with the **default path**, not `TESSDATA_PREFIX` if set via shell environment. 

To fix this, please add `path=TESSDATA_PREFIX` to all invocations of `get_languages`. 

In retrospect, I am surprised this did not cause trouble earlier...
