### ISSUE TITLE
Exception: File with ID=... already exists

### ISSUE THREAD

**Issue by beckstefan** [OCR-D/ocrd_tesserocr#147]
After running

```
'anybaseocr-binarize -I OCR-D-IMG -O OCR-D-BIN' \
'anybaseocr-crop -I OCR-D-BIN -O OCR-D-CROP'
```

in docker successfully, calling

```
docker run --rm -u $(id -u) -v /home/ocrd/workspace/test/:/data -w /data ocrd/all:maximum ocrd-tesserocr-deskew -I OCR-D-CROP -O OCR-D-DESKEW -P operation_level page -l DEBUG
```

results in

```2020-09-04 10:03:58,156.156 INFO root - Overriding log level globally to DEBUG
2020-09-04 10:03:58,157.157 DEBUG ocrd.resolver - Deriving dst_dir /data from /data/mets.xml
2020-09-04 10:03:58,157.157 DEBUG ocrd.resolver - workspace_from_url
mets_basename='mets.xml'
mets_url='/data/mets.xml'
src_baseurl='/data'
dst_dir='/data'
2020-09-04 10:03:58,157.157 DEBUG ocrd.resolver.download_to_directory - directory=|/data| url=|/data/mets.xml| basename=|mets.xml| if_exists=|skip| subdir=|None|
2020-09-04 10:03:58,157.157 DEBUG ocrd.resolver.download_to_directory - Stop early, src_path and dst_path are the same: '/data/mets.xml' (url: '/data/mets.xml')
2020-09-04 10:03:58,158.158 DEBUG ocrd.workspace_validator - input_file_grp=['OCR-D-CROP'] output_file_grp=['OCR-D-DESKEW']
2020-09-04 10:03:58,158.158 DEBUG ocrd.processor - Running processor <class 'ocrd_tesserocr.deskew.TesserocrDeskew'>
2020-09-04 10:03:58,159.159 DEBUG ocrd.processor - Processor instance <ocrd_tesserocr.deskew.TesserocrDeskew object at 0x7fe987f0c4a8> (ocrd-tesserocr-deskew v0.9.1 doing preprocessing/optimization/deskewing)
2020-09-04 10:03:58,244.244 INFO processor.TesserocrDeskew - INPUT FILE 0 / img-0001.tif
2020-09-04 10:03:58,244.244 DEBUG ocrd.workspace - download_file <OcrdFile fileGrp=OCR-D-CROP, ID=OCR-D-CROP-0001.tif, mimetype=application/vnd.prima.page+xml, url=OCR-D-CROP/OCR-D-CROP-0001.tif.xml, local_filename=OCR-D-CROP/OCR-D-CROP-0001.tif.xml]/>  [_recursion_count=0]
2020-09-04 10:03:58,248.248 DEBUG ocrd.workspace - download_file <OcrdFile fileGrp=OCR-D-IMG, ID=OCR-D-IMG-0001.tif, mimetype=image/tiff, url=OCR-D-IMG/0001.tif, local_filename=OCR-D-IMG/0001.tif]/>  [_recursion_count=0]
2020-09-04 10:03:58,255.255 DEBUG PIL.TiffImagePlugin - *** TiffImageFile._open ***
... way more PIL debug messages ...
2020-09-04 10:03:58,289.289 DEBUG ocrd.workspace - page 'img-0001.tif' has border, orientation=0 skew=0.00
2020-09-04 10:03:58,289.289 DEBUG ocrd.workspace - Using AlternativeImage 2 (,binarized,cropped) for page 'img-0001.tif'
2020-09-04 10:03:58,289.289 DEBUG ocrd.workspace - download_file <OcrdFile fileGrp=OCR-D-CROP, ID=OCR-D-CROP-0001.tif-IMG, mimetype=image/png, url=OCR-D-CROP/OCR-D-CROP-0001.tif-IMG.png, local_filename=OCR-D-CROP/OCR-D-CROP-0001.tif-IMG.png]/>  [_recursion_count=0]
2020-09-04 10:03:58,290.290 DEBUG PIL.PngImagePlugin - STREAM b'IHDR' 16 13
2020-09-04 10:03:58,290.290 DEBUG PIL.PngImagePlugin - STREAM b'IDAT' 41 61933
2020-09-04 10:03:58,306.306 DEBUG ocrd.workspace - Using explicitly set page border '196,283 1960,283 1960,2425 196,2425' for page 'img-0001.tif'
2020-09-04 10:03:58,306.306 DEBUG ocrd_utils.coords.shift_coordinates - shifting coordinates by [-196 -283]
2020-09-04 10:03:58,307.307 INFO processor.TesserocrDeskew - Page 'img-0001.tif' images will use 400 DPI from image meta-data
2020-09-04 10:03:58,307.307 INFO processor.TesserocrDeskew - Deskewing on 'page' level in page 'img-0001.tif'
2020-09-04 10:03:58,622.622 INFO processor.TesserocrDeskew - applying OSD orientation result 0° clockwise with high confidence 10 in page 'img-0001.tif'
2020-09-04 10:03:58,622.622 INFO processor.TesserocrDeskew - applying OSD script  result "Latin" with high confidence 13 in page 'img-0001.tif'
2020-09-04 10:03:59,026.026 INFO processor.TesserocrDeskew - orientation/deskewing for page 'img-0001.tif': PAGE_UP / LEFT_TO_RIGHT / TOP_TO_BOTTOM / 0.000°
2020-09-04 10:03:59,080.080 DEBUG ocrd.workspace - outputfile file_grp=OCR-D-DESKEW local_filename=OCR-D-DESKEW/OCR-D-DESKEW-0001.tif.png content=True
2020-09-04 10:03:59,082.082 INFO ocrd.workspace - created file ID: OCR-D-DESKEW-0001.tif, file_grp: OCR-D-DESKEW, path: OCR-D-DESKEW/OCR-D-DESKEW-0001.tif.png
2020-09-04 10:03:59,082.082 DEBUG ocrd.workspace - outputfile file_grp=OCR-D-DESKEW local_filename=OCR-D-DESKEW/OCR-D-DESKEW-0001.tif.xml content=True
Traceback (most recent call last):
  File "/usr/bin/ocrd-tesserocr-deskew", line 8, in <module>
    sys.exit(ocrd_tesserocr_deskew())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd_tesserocr/cli.py", line 46, in ocrd_tesserocr_deskew
    return ocrd_cli_wrap_processor(TesserocrDeskew, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd/decorators.py", line 102, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd/processor/helpers.py", line 69, in run_processor
    processor.process()
  File "/usr/lib/python3.6/site-packages/ocrd_tesserocr/deskew.py", line 141, in process
    content=to_xml(pcgts))
  File "/usr/lib/python3.6/site-packages/ocrd/workspace.py", line 223, in add_file
    ret = self.mets.add_file(file_grp, **kwargs)
  File "/usr/lib/python3.6/site-packages/ocrd_models/ocrd_mets.py", line 262, in add_file
    raise Exception("File with ID='%s' already exists" % ID)
Exception: File with ID='OCR-D-DESKEW-0001.tif' already exists
```

In my `mets.xml` the ID is non-existing, before and after the above call, however, a file `OCR-D-DESKEW/OCR-D-DESKEW-0001.tif.png` does exist.

**Comment by bertsky** [comment]
Thanks @beckstefan for the comprehensive report!

There's something strange going on here with your page IDs (they have a filename suffix), so there might also be a bug in core's `make_file_id`, but `ocrd-tesserocr-deskew` definitely also has a bug:

https://github.com/OCR-D/ocrd_tesserocr/blob/49e93b99915e064b71617dad15de60075d5ab01d/ocrd_tesserocr/deskew.py#L290

That should be `file_id + '.IMG-DESKEW'`. I'll prepare a PR right away.

**Comment by kba** [comment]
> There's something strange going on here with your page IDs (they have a filename suffix)

@beckstefan Thanks for the report. Can you please post the `mets.xml` so I can investigate why the extensions on the `mets:file/@ID`?

**Comment by bertsky** [comment]
@beckstefan here's a recipe for testing #148 in a Docker installation:

    docker pull ocrd/all:maximum-git
    docker run --rm -it -u $(id -u) -v /home/ocrd/workspace/test/:/data -w /data ocrd/all:maximum-git /bin/bash
    cd /build/ocrd_tesserocr
    git pull origin pull/148/head
    cd /data
    ocrd-tesserocr-deskew -I OCR-D-CROP -O OCR-D-DESKEW -P operation_level page -l DEBUG

(you might have to add `--overwrite` to the last command)

**Comment by beckstefan** [comment]
@bertsky Yes, this works. Thanks!

@kba Here's the `mets.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-0.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.xsd http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version17/mets.v1-7.xsd http://www.loc.gov/mix/v10 http://www.loc.gov/standards/mix/mix10/mix10.xsd">
  <mets:metsHdr CREATEDATE="2020-09-03T15:14:50.333198">
    <mets:agent TYPE="OTHER" OTHERTYPE="SOFTWARE" ROLE="CREATOR">
      <mets:name>ocrd/core v2.15.0</mets:name>
    </mets:agent>
  </mets:metsHdr>
  <mets:dmdSec ID="DMDLOG_0001">
    <mets:mdWrap MDTYPE="MODS">
      <mets:xmlData>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3">
          <mods:identifier type="purl">34cef89c-11e8-4975-86c2-f17317f5ffa4</mods:identifier>
        </mods:mods>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:amdSec ID="AMD">
    </mets:amdSec>
  <mets:fileSec>
    <mets:fileGrp USE="OCR-D-IMG">
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0001.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0001.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0002.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0002.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0003.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0003.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0004.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0004.tif"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap TYPE="PHYSICAL">
    <mets:div TYPE="physSequence">
      <mets:div TYPE="page" ID="img-0001.tif">
        <mets:fptr FILEID="OCR-D-IMG-0001.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0002.tif">
        <mets:fptr FILEID="OCR-D-IMG-0002.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0003.tif">
        <mets:fptr FILEID="OCR-D-IMG-0003.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0004.tif">
        <mets:fptr FILEID="OCR-D-IMG-0004.tif"/>
      </mets:div>
    </mets:div>
  </mets:structMap>
</mets:mets>
```

and after both tools from above have run:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="info:lc/xmlns/premis-v2 http://www.loc.gov/standards/premis/v2/premis-v2-0.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.xsd http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version17/mets.v1-7.xsd http://www.loc.gov/mix/v10 http://www.loc.gov/standards/mix/mix10/mix10.xsd">
  <mets:metsHdr CREATEDATE="2020-09-03T15:14:50.333198">
    <mets:agent TYPE="OTHER" OTHERTYPE="SOFTWARE" ROLE="CREATOR">
      <mets:name>ocrd/core v2.15.0</mets:name>
    </mets:agent>
    <mets:agent TYPE="OTHER" OTHERTYPE="SOFTWARE" ROLE="OTHER" OTHERROLE="preprocessing/optimization/binarization">
      <mets:name>ocrd-anybaseocr-binarize v1.0.1</mets:name>
    </mets:agent>
    <mets:agent TYPE="OTHER" OTHERTYPE="SOFTWARE" ROLE="OTHER" OTHERROLE="preprocessing/optimization/cropping">
      <mets:name>ocrd-anybaseocr-crop v1.0.1</mets:name>
    </mets:agent>
  </mets:metsHdr>
  <mets:dmdSec ID="DMDLOG_0001">
    <mets:mdWrap MDTYPE="MODS">
      <mets:xmlData>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3">
          <mods:identifier type="purl">34cef89c-11e8-4975-86c2-f17317f5ffa4</mods:identifier>
        </mods:mods>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:amdSec ID="AMD">
    </mets:amdSec>
  <mets:fileSec>
    <mets:fileGrp USE="OCR-D-IMG">
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0001.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0001.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0002.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0002.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0003.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0003.tif"/>
      </mets:file>
      <mets:file MIMETYPE="image/tiff" ID="OCR-D-IMG-0004.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-IMG/0004.tif"/>
      </mets:file>
    </mets:fileGrp>
    <mets:fileGrp USE="OCR-D-BIN">
      <mets:file MIMETYPE="image/png" ID="OCR-D-BIN-0001.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0001.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-BIN-0001.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0001.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-BIN-0002.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0002.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-BIN-0002.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0002.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-BIN-0003.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0003.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-BIN-0003.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0003.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-BIN-0004.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0004.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-BIN-0004.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-BIN/OCR-D-BIN-0004.tif.xml"/>
      </mets:file>
    </mets:fileGrp>
    <mets:fileGrp USE="OCR-D-CROP">
      <mets:file MIMETYPE="image/png" ID="OCR-D-CROP-0001.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0001.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-CROP-0001.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0001.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-CROP-0002.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0002.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-CROP-0002.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0002.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-CROP-0003.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0003.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-CROP-0003.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0003.tif.xml"/>
      </mets:file>
      <mets:file MIMETYPE="image/png" ID="OCR-D-CROP-0004.tif-IMG">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0004.tif-IMG.png"/>
      </mets:file>
      <mets:file MIMETYPE="application/vnd.prima.page+xml" ID="OCR-D-CROP-0004.tif">
        <mets:FLocat LOCTYPE="OTHER" OTHERLOCTYPE="FILE" xlink:href="OCR-D-CROP/OCR-D-CROP-0004.tif.xml"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap TYPE="PHYSICAL">
    <mets:div TYPE="physSequence">
      <mets:div TYPE="page" ID="img-0001.tif">
        <mets:fptr FILEID="OCR-D-IMG-0001.tif"/>
        <mets:fptr FILEID="OCR-D-BIN-0001.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-BIN-0001.tif"/>
        <mets:fptr FILEID="OCR-D-CROP-0001.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-CROP-0001.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0002.tif">
        <mets:fptr FILEID="OCR-D-IMG-0002.tif"/>
        <mets:fptr FILEID="OCR-D-BIN-0002.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-BIN-0002.tif"/>
        <mets:fptr FILEID="OCR-D-CROP-0002.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-CROP-0002.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0003.tif">
        <mets:fptr FILEID="OCR-D-IMG-0003.tif"/>
        <mets:fptr FILEID="OCR-D-BIN-0003.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-BIN-0003.tif"/>
        <mets:fptr FILEID="OCR-D-CROP-0003.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-CROP-0003.tif"/>
      </mets:div>
      <mets:div TYPE="page" ID="img-0004.tif">
        <mets:fptr FILEID="OCR-D-IMG-0004.tif"/>
        <mets:fptr FILEID="OCR-D-BIN-0004.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-BIN-0004.tif"/>
        <mets:fptr FILEID="OCR-D-CROP-0004.tif-IMG"/>
        <mets:fptr FILEID="OCR-D-CROP-0004.tif"/>
      </mets:div>
    </mets:div>
  </mets:structMap>
</mets:mets>
```

**Comment by stweil** [comment]
Same error here with standard workflow and urn:nbn:de:bsz:180-digad-8419.
