### ISSUE TITLE
Setting locale fails on macOS

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_tesserocr#71]
See protocol:

    $ ocrd-tesserocr-recognize 
    Traceback (most recent call last):
      File "/Users/stweil/ocr-d/20190824/bin/ocrd-tesserocr-recognize", line 6, in <module>
        from ocrd_tesserocr.cli import ocrd_tesserocr_recognize
      File "/Users/stweil/ocr-d/20190824/lib/python3.7/site-packages/ocrd_tesserocr/__init__.py", line 7, in <module>
        locale.setlocale(locale.LC_ALL, 'C.UTF-8')
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 604, in setlocale
        return _setlocale(category, locale)
    locale.Error: unsupported locale setting

Setting the locale is no longer necessary for Tesseract 4.1.0 which is also the recommended stable version.

**Comment by stweil** [comment]
Python 3.7 seems to accept `locale.setlocale(locale.LC_ALL, 'C')` on macOS.

**Comment by stweil** [comment]
Pull request #72 handles this issue by catching the exception. It requires a recent version (4.1.0 or newer) of Tesseract on macOS.

**Comment by stweil** [comment]
The pull request was merged, so I close this issue.
